[programs.localnet]
lunaria-mint-token = "2CfjCszjTaj3y12JsFaxk6MGvqUAUF1kqSUhMDPJ9c9u"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/michaelyu/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
